Feature/fix tflite tests and examples
RidgeRun/r2inference pull request #116
Opened 2021-03-01 16:56 UTC by jsalas98

2021-03-01 20:40 UTC, fasm22 requested changes

2021-03-01 20:40 UTC, fasm22 commented on tests/unit/r2i/tflite/engine.cc
> +  int channels = 3;
Can we get number of channels from frame information someway? Just trying to avoid fixed numbers

2021-03-01 21:58 UTC, michaelgruner approved these changes

2021-03-02 14:37 UTC, fasm22 approved these changes

2021-03-02 14:47 UTC, merged