Feature/add nnapi tflite support
RidgeRun/r2inference pull request #128
Opened 2021-11-22 15:51 UTC by Edjchg

Add support for NNAPI delegegate with TensorFlow lite backend.

2021-11-23 15:20 UTC, lleon95 requested changes

2021-11-23 15:20 UTC, lleon95 commented on r2i/nnapi/engine.h
> +#include "tensorflow/lite/tools/evaluation/utils.h"
Move these headers (`tensorflow/*`) to the .cc, since they are not required here.

2021-11-23 15:43 UTC, lleon95 commented on meson.build
> +  configinc += include_directories('../recipe-sysroot/usr/include/tensorflow/lite/tools/make/downloads/flatbuffers/include')
We could adapt it as it is shown in the R2Inference guide:
![image](https://user-images.githubusercontent.com/7350785/143055869-7a99fcfe-bee5-4be7-8521-f4cff6d297be.png)

2021-11-26 17:22 UTC, Edjchg commented on r2i/nnapi/engine.cc
> +  this->number_of_threads = 1;
The default value greater than 0.

2021-11-26 19:30 UTC, lleon95 approved these changes

2021-11-26 19:30 UTC, lleon95 commented on r2i/iframeworkfactory.cc
> +#endif
Still missing

2021-11-26 19:30 UTC, lleon95 commented on r2i/nnapi/frameworkfactory.cc
> +#include "engine.h"
Still missing

2021-11-30 14:17 UTC, lleon95 commented on meson.build
> +  configinc += include_directories('../recipe-sysroot/usr/include/tensorflow/lite/tools/make/downloads/flatbuffers/include')
Please, also add the instructions over here:
https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Getting_started/Building_the_library

2021-11-30 14:19 UTC, lleon95 commented on r2i/iframeworkfactory.cc
> +#include "nnapi/frameworkfactory.h"
Still missing

2021-11-30 14:19 UTC, lleon95 commented on r2i/iframeworkfactory.cc
> +#include "nnapi/frameworkfactory.h"
still missing

2021-11-30 23:35 UTC, merged